### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by iwazaru** [itsananderson/node-web-server-cli#2]
Running web-server on Mac OS X 10.10 I got the following error:

    env: node\r: No such file or directory

Solved it by doing:

    sudo vim /usr/local/bin/web-server
    :set ff=unix
    :wq!

And now it works !

**Comment by itsananderson** [comment]
I swear I've fixed this like 3 times, but for some reason it keeps cropping up.

I was able to repro on an Ubuntu VM, but it's strange because that file has Unix newlines on Git. What I wonder is whether the npm registry didn't update the file previously when I fixed the line endings, because it was only whitespace changes.

Anyway, I published 1.0.1 with a small text tweak to that file, and when I installed it on the Ubuntu VM, it seemed to work properly. If you can confirm that it's fixed in OS X, we can close the issue, or I can test it later today when I get home.

**Comment by iwazaru** [comment]
1.0.1 works like a charm, thanks !
